branches:
  only:
  - master
language: python
python:
- 3.6 
install:
- pip install -r requirements.txt
script:
- pelican content
- fab publish
before_install:
- echo -e "Host nyayapati.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_11e96674d73c_key -iv $encrypted_11e96674d73c_iv -in deploy_keys.enc -out deploy_keys -d
- chmod 600 deploy_keys
- mv deploy_keys ~/.ssh/id_rsa

